### ISSUE TITLE
[Crash]: Conflict with Mythic Metals

### ISSUE THREAD

**Issue by KingCreeps** [Fuzss/helditemtooltips#2]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

v6.0.0-1.19.4

### Notes (Required)

Attempting to scroll over the drill from Mythic Metals causes the game to immediately CTD

### Crash Report (Required)

https://gist.github.com/KingCreeps/d7bbf5fab31b4555243f5e37f2b7e9fa

**Comment by Snow5Wolf** [comment]
This also apply to Carmot Staff from Mythic Metals on 1.19.2 , my game crashed when I use number hotkey to add the item to my hotbar

**Comment by Fuzss** [comment]
This is fixed for 1.20.1+. 1.19.4 is no longer supported.
