### ISSUE TITLE
[Suggestion]: color compatibly with tooltips+ when using default color option

### ISSUE THREAD

**Issue by Taleuxss** [Fuzss/helditemtooltips#3]
### Suggestion (Required)

https://modrinth.com/mod/tooltipsplus has colored titles for items that is very nice but they don't work with the held item tooltip unfortunately 
![image](https://github.com/Fuzss/helditemtooltips/assets/50016554/29f57c27-5c52-4f4d-a0bf-a8240bc78841)
![image](https://github.com/Fuzss/helditemtooltips/assets/50016554/762caa37-3761-435e-8456-d71e08ccc6fa)

**Comment by Fuzss** [comment]
It looks like that mod is not using the common Fabric Api hook for modifying tooltips (`ItemTooltipCallback`), they seem to be using Mixins instead, which I cannot support.
