### ISSUE TITLE
[Bug]: When cycling through items that are the same (e.g. two diamond pickaxes), the tooltip doesn't refresh its on-screen timer

### ISSUE THREAD

**Issue by ShinryuAspect** [Fuzss/helditemtooltips#4]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.0

### Notes (Required)

If I have, for example, two Enchanted Diamond Pickaxes in my hotbar (with different stats (durability, enchantments, etc.)) and I try to cycle through both of them, the time the tooltip stays visible doesn't refresh upon swaping. It doesn't seem to happen when the tools are renamed.

**Comment by Fuzss** [comment]
That's some behavior carried over from vanilla. Usually the item name is compared to determine when to render the tooltip again. I've now included an additional check for the selected hotbar slot, so when that changes the tooltip will appear again.
Coming to 1.20.4 only for now, might consider a backport later on.
