### ISSUE TITLE
[Suggestion]: Compatibility with other tooltip mods

### ISSUE THREAD

**Issue by dmyoung9** [Fuzss/helditemtooltips#6]
### Suggestion (Required)

It would be great if the tooltips displayed by this mod would take into consideration modifications made by other tooltip-related mods...

For example, this is a tooltip with [Clean Tooltips](https://modrinth.com/mod/clean-tooltips), [Durability Tooltip](https://modrinth.com/mod/durability-tooltip), and [Legendary Tooltips](https://modrinth.com/mod/legendary-tooltips) (along with [Eclectic Trove](https://modrinth.com/resourcepack/eclectic-trove-legendary-tooltips)):
![image](https://github.com/Fuzss/helditemtooltips/assets/101432365/a3abd7a2-4039-40f5-9313-d24a2f0743df)

But this is the held item tooltip for the same item:
![image](https://github.com/Fuzss/helditemtooltips/assets/101432365/020a40ab-63f9-4a3f-818b-2b3c3adce3c1)

Is it possible to support this?

**Comment by Fuzss** [comment]
Enable the `additional_information` config option for mod support. Clean Tooltips may not work since they don't use any of the mod apis for modifying tooltip lines, they just use a Mixin which I can't support.
